global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'siperpus-app'
    metrics_path: '/perpus-app/public/metrics' # Atur sesuai path web server/virtual host Anda (contoh: http://host.docker.internal/perpus-app/public/metrics atau http://host.docker.internal:8000/metrics)
    scrape_interval: 10s
    static_configs:
      - targets: ['host.docker.internal:80']
        labels:
          environment: 'production'
          app: 'siperpus'
